game:
  # Use 0 for random seed
  seed: 0

  # The name of the world to be used during the game. Will be deleted / recreated as required.
  game_world: 'uhc'

  # The number of teams to create
  teams: 15
  # How many players in a team
  team_size: 2