game:
  # Use 0 for random seed
  seed: 0

  # The name of the world to be used during the game. Will be deleted / recreated as required.
  game_world: 'uhc'

  # The number of teams to create
  teams: 15
  # How many players in a team
  team_size: 2

  # Initial order size (side length)
  border_size: 10000

  # Grace period length in minutes
  gp_length: 60

  # Scoreboard title (shown above game stats) - use & for colour and formatting codes (https://wiki.ess3.net/mc/)
  scoreboard_title: '&c&lUHC'