name: UHCPlugin
version: "1.0"
author: Samboy063
main: me.samboycoding.uhcplugin.UHCPlugin
commands:
  start:
    description: "Starts the game"
    usage: "/start"
  disableamnesty:
    description: "Disables no-pvp"
    usage: "/disableamnesty"